# DAY 1

This repo contains an introduction to [Numpy](https://numpy.org/).

Numpy stands for Numerical Python. It is useful for handling operations on large amount of data. Datasets comes in all forms like textual, audio, video, etc. Numpy helps in representing these type of data in the form of arrays. The dimension of the array depends on the type of data we are dealing with. Numpy package is useful in handling such numerical arrays and operate on them.

References : 

* [Numpy official Documentation](https://numpy.org/)
* [Introduction to Numpy](https://jakevdp.github.io/PythonDataScienceHandbook/02.00-introduction-to-numpy.html)


In [2]:
#Importing numpy

import numpy as np #np is the alias

np.__version__

'1.16.2'

## Difference between a list and a Numpy Array

* Each item in the Python list contains its own type info, reference count and other information.
* At the implementation level, Numpy Array contains a single pointer to a contiguous block of data, whereas python list contains a pointer to a block of pointers, each of which in turn points to a full python object.
* A list is flexible and can store data of all types; A Numpy Array is a fixed type array
* A Numpy array is more efficient in storing and manipulating data than a list.


### Example of Fixed type Array

In [5]:
import array

arr = array.array('i', [1, 2, 3, 4, 5, 6])

#Returns the start address in memory and number of elements in array
arr.buffer_info()  

(140265291152576, 6)

### Create arrays from Python List

In [9]:
list_same_type = [1, 2, 3, 4, 5]

np.array(list_same_type)

array([1, 2, 3, 4, 5])

In [7]:
list_diff_type = [1.0, 2, 3, 4]

#If type is different, Numpy upcasts the elements if possible; Here, integer elements are upcasted to float type 
np.array(list_diff_type)

array([1., 2., 3., 4.])

In [8]:
list_diff_type1 = [1.0, 2, 3, 4, "anu"]

np.array(list_diff_type1)

array(['1.0', '2', '3', '4', 'anu'], dtype='<U32')

If we wish to explicitly set the data type of the resulting array, we use **dtype** keyword

In [10]:
np.array(list_same_type, dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

Numpy Arrays can be multi-dimensional

In [11]:
np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
np.array([range(i, i+7) for i in range(4)])

array([[0, 1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6, 7],
       [2, 3, 4, 5, 6, 7, 8],
       [3, 4, 5, 6, 7, 8, 9]])

### Create arrays from scratch (without using lists)

For large amount of data, it is beneficial to create arrays from scratch using routines built into Numpy

In [19]:
#Create an array, length of 10, filled with zeros
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
#Create a two dimensional array filled with 1
np.ones((2,2), dtype='float')

array([[1., 1.],
       [1., 1.]])

In [23]:
#Create a two dimensional array filled with single value
np.full((2,2), 25)

#Create a one dimensional array filled with single value
np.full(2, 25)

array([25, 25])

In [24]:
#Create a linear sequence 
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])